sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t bxhu/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true bxhu/react-test npm test

after_success:
  - docker build -t bxhu/dockerfibonacci-client ./client
  - docker build -t bxhu/dockerfibonacci-server ./server
  - docker build -t bxhu/dockerfibonacci-worker ./worker
  - docker build -t bxhu/dockerfibonacci-nginx ./nginx
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push bxhu/dockerfibonacci-client
  - docker push bxhu/dockerfibonacci-server
  - docker push bxhu/dockerfibonacci-worker
  - docker push bxhu/dockerfibonacci-nginx

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: dockerfibonacci
  env: Dockerfibonacci-env
  bucket_name: elasticbeanstalk-us-east-1-235120284424
  bucket_path: docker-fibonacci
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY